### ISSUE TITLE
Infinite loop problem

### ISSUE THREAD

**Issue by ttnppedr** [LanKuDot/game_modules#23] opened 2021-06-10 09:26 UTC
In ListBank if size of contents is zero it will encounter a infinite loop problem while executing.

**Comment by LanKuDot** [comment] 2021-06-10 09:32
It is caused by rounding the initial content ID in the `ListBox.cs`. https://github.com/LanKuDot/game_modules/blob/master/CircularScrollingList/ListBox.cs#L245
It will be fixed in the next version, and report an exception instead.

**Comment by LanKuDot** [comment] 2021-08-06 15:40
Fixed in version 5. It is allowed to have no content in the list bank.

**Closed by LanKuDot** 2021-08-06 15:40 UTC
Labels: bug
